# Generated by Django 5.2.17 on 2026-09-24 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rail', models.CharField(choices=[('bitlibera_offramp', 'BitLibera off-ramp'), ('bitlibera_onramp', 'BitLibera on-ramp'), ('blink_direct', 'Blink direct')], max_length=32)),
                ('order_id', models.CharField(help_text='BitLibera reference — idempotency key.', max_length=64, unique=True)),
                ('payment_request', models.TextField(blank=True, default='')),
                ('amount_sats', models.BigIntegerField(blank=True, null=True)),
                ('amount_bif', models.BigIntegerField(blank=True, null=True)),
                ('lumicash_phone', models.CharField(blank=True, default='', max_length=30)),
                ('lines', models.JSONField(blank=True, default=list, help_text='Frozen cart snapshots [{product_id, quantity, unit_price, unit_cost}].')),
                ('currency', models.CharField(default='BIF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('failed', 'failed'), ('expired', 'expired')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.business')),
                ('financial_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ledger.financialevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='payments_pa_busines_0cb2e2_idx')],
            },
        ),
    ]
