# Generated by Django 5.2.17 on 2026-09-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_tendered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rail',
            field=models.CharField(choices=[('bitlibera_offramp', 'BitLibera off-ramp'), ('bitlibera_onramp', 'BitLibera on-ramp'), ('blink_direct', 'Blink direct'), ('cash', 'Cash')], max_length=32),
        ),
    ]
