# Generated by Django 5.2.17 on 2026-09-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('checkout', 'Cart checkout'), ('subscription', 'SaaS subscription')], default='checkout', help_text='What the Payment pays for: checkout or subscription (doc §41).', max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_currency',
            field=models.CharField(choices=[('BIF', 'Burundian Franc'), ('USD', 'US Dollar'), ('SAT', 'Sats')], default='BIF', help_text='Currency FOBOS expects to receive (doc §46).', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('BIF', 'Burundian Franc'), ('USD', 'US Dollar'), ('SAT', 'Sats')], default='BIF', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('pending', 'pending'), ('paid', 'paid'), ('failed', 'failed'), ('expired', 'expired'), ('cancelled', 'cancelled')], default='pending', max_length=16),
        ),
    ]
