# Generated by Django 5.2.17 on 2026-09-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_amount_tendered_alter_payment_rail'),
        ('payments', '0002_payment_purpose_payment_settlement_currency_and_more'),
    ]

    operations = [
    ]
