# Generated by Django 5.2.17 on 2026-09-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_merge_20260925_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Settlement currency units per one unit of the checkout currency.', max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate_source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_amount',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Quoted amount in settlement_currency when the invoice was created.', max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(help_text='Unique checkout reference and idempotency key.', max_length=64, unique=True),
        ),
    ]
