# Generated by Django 5.2.17 on 2026-09-24 01:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PAYMENT_CONFIRMED', 'Payment confirmed'), ('PAYMENT_PENDING', 'Payment pending')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(choices=[('BIF', 'Burundian Franc'), ('USD', 'US Dollar'), ('SAT', 'Sats')], default='BIF', max_length=3)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('bitlibera_offramp', 'BitLibera off-ramp'), ('bitlibera_onramp', 'BitLibera on-ramp'), ('blink_direct', 'Blink direct')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('failed', 'failed')], max_length=16)),
                ('actor', models.CharField(blank=True, default='', max_length=150)),
                ('reference', models.CharField(blank=True, default='', max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_events', to='accounts.business')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=8)),
                ('account', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('BIF', 'Burundian Franc'), ('USD', 'US Dollar'), ('SAT', 'Sats')], default='BIF', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts.business')),
                ('financial_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='ledger.financialevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financialevent',
            index=models.Index(fields=['business', 'timestamp'], name='ledger_fina_busines_b5a6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='financialevent',
            index=models.Index(fields=['business', 'type', 'status'], name='ledger_fina_busines_d92dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['business', 'account', 'created_at'], name='ledger_ledg_busines_a8769b_idx'),
        ),
    ]
