# Generated by Django 5.2.17 on 2026-09-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialevent',
            name='source',
            field=models.CharField(choices=[('bitlibera_offramp', 'BitLibera off-ramp'), ('bitlibera_onramp', 'BitLibera on-ramp'), ('blink_direct', 'Blink direct'), ('cash', 'Cash')], max_length=32),
        ),
    ]
