# Generated by Django 5.2.17 on 2026-09-24 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('automation', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationexecution',
            name='financial_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_executions', to='ledger.financialevent'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='accounts.business'),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.automationrule'),
        ),
    ]
