# Generated by Django 5.2.17 on 2026-09-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, help_text='Code128 PNG image of `barcode`, persisted on the media volume.', null=True, upload_to='barcodes/'),
        ),
    ]
