# Generated by Django 5.2.17 on 2026-09-24 10:47

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_barcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, help_text='Code128 PNG image of `barcode`, persisted on the media volume.', null=True, upload_to=products.models.barcode_image_path),
        ),
    ]
