# Generated by Django 5.2.17 on 2026-09-24 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0003_alter_product_barcode_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sale', 'sale'), ('restock', 'restock'), ('adjustment', 'adjustment'), ('return', 'return')], max_length=16)),
                ('qty_delta', models.IntegerField(help_text='Signed: negative = out, positive = in.')),
                ('qty_after', models.PositiveIntegerField(help_text='Resulting stock after this movement.')),
                ('reference', models.CharField(blank=True, help_text='order_id / financial_event_id / invoice_id.', max_length=64, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['business', 'product', '-created_at'], name='products_st_busines_ca9e1a_idx'), models.Index(fields=['business', 'type', '-created_at'], name='products_st_busines_b353e7_idx')],
            },
        ),
    ]
